services:
  db:
    image: postgres:latest
    container_name: postgres_db1
    environment:
      POSTGRES_USER: fausto
      POSTGRES_PASSWORD: passfausto
      POSTGRES_DB: pdfsender
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: